### ISSUE TITLE
python: can't open file 'bin/demo.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by prasetyoandi** [openai/orrb#1]

**Comment by michalvavrecka** [comment]
cannot find demo.py after install

**Comment by haudren** [comment]
Neither `demo.py` , `benchmark.py` nor `demo_keras.py` are present. Is this intended?

**Comment by prasetyoandi** [comment]
did i miss a step? @lilianweng @welinder @maciekcc

**Comment by lilianweng** [comment]
Sorry about the inconvenience. Those files are added now.
