### ISSUE TITLE
ValueError: Missing run.sh in package: StandaloneRenderer-Linux-x86_64-20190514 (/home/nimble/Downloads/crm/orrb).

### ISSUE THREAD

**Issue by Cmadhava** [openai/orrb#3]
I installed the requirements and when I tried to run 
"python bin/demo.py interactive" I got the error same as the title.

**Comment by maciekcc** [comment]
Did you 'install-prebuilt.sh'. Is the 'run.sh' actually missing from that directory? Do you have `ORRB_BINARIES_DIR` set-up correctly?

**Comment by Cmadhava** [comment]
I did it from scratch again and it worked . Thanks!
